import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen overflow-hidden bg-gray-50`}>
        <div className="flex h-full flex-col">
          <Header />

          {/* Main scrollable area */}
          <main className="flex-1 overflow-y-auto pt-14 md:pt-16 pb-14 bg-gray-50">
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
