import type { IconType } from 'react-icons';
import {
  FaStar,
  FaFire,
  FaBolt,
  FaTrophy,
  FaGift,
  FaTag,
  FaHeart,
  FaCrown,
  FaGem,
  FaCheckCircle,
  FaBell,
  FaBookmark,
  FaFlag,
  FaThumbsUp,
  FaShieldAlt,
  FaRocket,
  FaShoppingCart,
  FaShoppingBag,
  FaStore,
  FaWallet,
  FaCreditCard,
  FaMoneyBill,
  FaMoneyBillWave,
  FaCoins,
  FaBarcode,
  FaBox,
  FaBoxOpen,
  FaTruck,
  FaWarehouse,
  FaReceipt,
  FaPercent,
  FaHandshake,
  FaLaptop,
  FaMobileAlt,
  FaDesktop,
  FaTabletAlt,
  FaKeyboard,
  FaCameraRetro,
  FaVideo,
  FaTv,
  FaGamepad,
  FaBatteryFull,
  FaHeadphones,
  FaMicrophone,
  FaWifi,
  FaPrint,
  FaRobot,
  FaCode,
  FaHome,
  FaBed,
  FaBath,
  FaKey,
  FaLock,
  FaLightbulb,
  FaSnowflake,
  FaThermometerHalf,
  FaFan,
  FaBroom,
  FaTools,
  FaCar,
  FaBus,
  FaMotorcycle,
  FaBicycle,
  FaPlane,
  FaShip,
  FaTrain,
  FaHelicopter,
  FaFutbol,
  FaBasketballBall,
  FaFootballBall,
  FaBaseballBall,
  FaGolfBall,
  FaTableTennis,
  FaBowlingBall,
  FaDumbbell,
  FaRunning,
  FaSwimmer,
  FaBiking,
  FaPalette,
  FaPaintBrush,
  FaMusic,
  FaGuitar,
  FaDrum,
  FaFilm,
  FaTheaterMasks,
  FaBook,
  FaBookOpen,
  FaUtensils,
  FaCoffee,
  FaBeer,
  FaWineGlass,
  FaHamburger,
  FaPizzaSlice,
  FaHotdog,
  FaIceCream,
  FaCookieBite,
  FaCarrot,
  FaAppleAlt,
  FaPepperHot,
  FaDog,
  FaCat,
  FaHorse,
  FaFish,
  FaPaw,
  FaDove,
  FaCrow,
  FaFrog,
  FaDragon,
  FaSpider,
  FaHippo,
  FaOtter,
  FaFeatherAlt,
  FaKiwiBird,
  FaUser,
  FaUsers,
  FaUserFriends,
  FaChild,
  FaBaby,
  FaUserTie,
  FaUserGraduate,
  FaWrench,
  FaHammer,
  FaCog,
  FaScrewdriver,
  FaClipboard,
  FaRulerCombined,
  FaIndustry,
  FaHardHat,
  FaFlask,
} from 'react-icons/fa';

export interface IconEntry {
  id: string;
  label: string;
  component: IconType;
}

export interface IconGroup {
  label: string;
  icons: IconEntry[];
}

export const ICON_GROUPS: IconGroup[] = [
  {
    label: 'Popular',
    icons: [
      { id: 'FaStar', label: 'Star', component: FaStar },
      { id: 'FaFire', label: 'Fire', component: FaFire },
      { id: 'FaBolt', label: 'Bolt', component: FaBolt },
      { id: 'FaTrophy', label: 'Trophy', component: FaTrophy },
      { id: 'FaGift', label: 'Gift', component: FaGift },
      { id: 'FaTag', label: 'Tag', component: FaTag },
      { id: 'FaHeart', label: 'Heart', component: FaHeart },
      { id: 'FaCrown', label: 'Crown', component: FaCrown },
      { id: 'FaGem', label: 'Gem', component: FaGem },
      { id: 'FaCheckCircle', label: 'Check Circle', component: FaCheckCircle },
      { id: 'FaBell', label: 'Bell', component: FaBell },
      { id: 'FaBookmark', label: 'Bookmark', component: FaBookmark },
      { id: 'FaFlag', label: 'Flag', component: FaFlag },
      { id: 'FaThumbsUp', label: 'Thumbs Up', component: FaThumbsUp },
      { id: 'FaShieldAlt', label: 'Shield', component: FaShieldAlt },
      { id: 'FaRocket', label: 'Rocket', component: FaRocket },
    ],
  },
  {
    label: 'Commerce',
    icons: [
      { id: 'FaShoppingCart', label: 'Shopping Cart', component: FaShoppingCart },
      { id: 'FaShoppingBag', label: 'Shopping Bag', component: FaShoppingBag },
      { id: 'FaStore', label: 'Store', component: FaStore },
      { id: 'FaWallet', label: 'Wallet', component: FaWallet },
      { id: 'FaCreditCard', label: 'Credit Card', component: FaCreditCard },
      { id: 'FaMoneyBill', label: 'Money Bill', component: FaMoneyBill },
      { id: 'FaMoneyBillWave', label: 'Money Wave', component: FaMoneyBillWave },
      { id: 'FaCoins', label: 'Coins', component: FaCoins },
      { id: 'FaBarcode', label: 'Barcode', component: FaBarcode },
      { id: 'FaBox', label: 'Box', component: FaBox },
      { id: 'FaBoxOpen', label: 'Box Open', component: FaBoxOpen },
      { id: 'FaTruck', label: 'Truck', component: FaTruck },
      { id: 'FaWarehouse', label: 'Warehouse', component: FaWarehouse },
      { id: 'FaReceipt', label: 'Receipt', component: FaReceipt },
      { id: 'FaPercent', label: 'Percent', component: FaPercent },
      { id: 'FaHandshake', label: 'Handshake', component: FaHandshake },
    ],
  },
  {
    label: 'Technology',
    icons: [
      { id: 'FaLaptop', label: 'Laptop', component: FaLaptop },
      { id: 'FaMobileAlt', label: 'Mobile', component: FaMobileAlt },
      { id: 'FaDesktop', label: 'Desktop', component: FaDesktop },
      { id: 'FaTabletAlt', label: 'Tablet', component: FaTabletAlt },
      { id: 'FaKeyboard', label: 'Keyboard', component: FaKeyboard },
      { id: 'FaCameraRetro', label: 'Camera', component: FaCameraRetro },
      { id: 'FaVideo', label: 'Video', component: FaVideo },
      { id: 'FaTv', label: 'TV', component: FaTv },
      { id: 'FaGamepad', label: 'Gamepad', component: FaGamepad },
      { id: 'FaBatteryFull', label: 'Battery', component: FaBatteryFull },
      { id: 'FaHeadphones', label: 'Headphones', component: FaHeadphones },
      { id: 'FaMicrophone', label: 'Microphone', component: FaMicrophone },
      { id: 'FaWifi', label: 'Wifi', component: FaWifi },
      { id: 'FaPrint', label: 'Printer', component: FaPrint },
      { id: 'FaRobot', label: 'Robot', component: FaRobot },
      { id: 'FaCode', label: 'Code', component: FaCode },
    ],
  },
  {
    label: 'Home',
    icons: [
      { id: 'FaHome', label: 'Home', component: FaHome },
      { id: 'FaBed', label: 'Bed', component: FaBed },
      { id: 'FaBath', label: 'Bath', component: FaBath },
      { id: 'FaKey', label: 'Key', component: FaKey },
      { id: 'FaLock', label: 'Lock', component: FaLock },
      { id: 'FaLightbulb', label: 'Lightbulb', component: FaLightbulb },
      { id: 'FaSnowflake', label: 'Snowflake', component: FaSnowflake },
      { id: 'FaThermometerHalf', label: 'Thermometer', component: FaThermometerHalf },
      { id: 'FaFan', label: 'Fan', component: FaFan },
      { id: 'FaBroom', label: 'Broom', component: FaBroom },
      { id: 'FaTools', label: 'Home Tools', component: FaTools },
    ],
  },
  {
    label: 'Vehicles',
    icons: [
      { id: 'FaCar', label: 'Car', component: FaCar },
      { id: 'FaBus', label: 'Bus', component: FaBus },
      { id: 'FaMotorcycle', label: 'Motorcycle', component: FaMotorcycle },
      { id: 'FaBicycle', label: 'Bicycle', component: FaBicycle },
      { id: 'FaPlane', label: 'Plane', component: FaPlane },
      { id: 'FaShip', label: 'Ship', component: FaShip },
      { id: 'FaTrain', label: 'Train', component: FaTrain },
      { id: 'FaHelicopter', label: 'Helicopter', component: FaHelicopter },
    ],
  },
  {
    label: 'Sports',
    icons: [
      { id: 'FaFutbol', label: 'Soccer', component: FaFutbol },
      { id: 'FaBasketballBall', label: 'Basketball', component: FaBasketballBall },
      { id: 'FaFootballBall', label: 'Football', component: FaFootballBall },
      { id: 'FaBaseballBall', label: 'Baseball', component: FaBaseballBall },
      { id: 'FaGolfBall', label: 'Golf', component: FaGolfBall },
      { id: 'FaTableTennis', label: 'Table Tennis', component: FaTableTennis },
      { id: 'FaBowlingBall', label: 'Bowling', component: FaBowlingBall },
      { id: 'FaDumbbell', label: 'Dumbbell', component: FaDumbbell },
      { id: 'FaRunning', label: 'Running', component: FaRunning },
      { id: 'FaSwimmer', label: 'Swimming', component: FaSwimmer },
      { id: 'FaBiking', label: 'Cycling', component: FaBiking },
    ],
  },
  {
    label: 'Art & Music',
    icons: [
      { id: 'FaPalette', label: 'Palette', component: FaPalette },
      { id: 'FaPaintBrush', label: 'Paint Brush', component: FaPaintBrush },
      { id: 'FaMusic', label: 'Music', component: FaMusic },
      { id: 'FaGuitar', label: 'Guitar', component: FaGuitar },
      { id: 'FaDrum', label: 'Drum', component: FaDrum },
      { id: 'FaFilm', label: 'Film', component: FaFilm },
      { id: 'FaTheaterMasks', label: 'Theater', component: FaTheaterMasks },
      { id: 'FaBook', label: 'Book', component: FaBook },
      { id: 'FaBookOpen', label: 'Book Open', component: FaBookOpen },
    ],
  },
  {
    label: 'Food',
    icons: [
      { id: 'FaUtensils', label: 'Utensils', component: FaUtensils },
      { id: 'FaCoffee', label: 'Coffee', component: FaCoffee },
      { id: 'FaBeer', label: 'Beer', component: FaBeer },
      { id: 'FaWineGlass', label: 'Wine Glass', component: FaWineGlass },
      { id: 'FaHamburger', label: 'Hamburger', component: FaHamburger },
      { id: 'FaPizzaSlice', label: 'Pizza', component: FaPizzaSlice },
      { id: 'FaHotdog', label: 'Hotdog', component: FaHotdog },
      { id: 'FaIceCream', label: 'Ice Cream', component: FaIceCream },
      { id: 'FaCookieBite', label: 'Cookie', component: FaCookieBite },
      { id: 'FaCarrot', label: 'Carrot', component: FaCarrot },
      { id: 'FaAppleAlt', label: 'Apple', component: FaAppleAlt },
      { id: 'FaPepperHot', label: 'Pepper', component: FaPepperHot },
    ],
  },
  {
    label: 'Animals',
    icons: [
      { id: 'FaDog', label: 'Dog', component: FaDog },
      { id: 'FaCat', label: 'Cat', component: FaCat },
      { id: 'FaHorse', label: 'Horse', component: FaHorse },
      { id: 'FaFish', label: 'Fish', component: FaFish },
      { id: 'FaPaw', label: 'Paw', component: FaPaw },
      { id: 'FaDove', label: 'Dove', component: FaDove },
      { id: 'FaCrow', label: 'Crow', component: FaCrow },
      { id: 'FaFrog', label: 'Frog', component: FaFrog },
      { id: 'FaDragon', label: 'Dragon', component: FaDragon },
      { id: 'FaSpider', label: 'Spider', component: FaSpider },
      { id: 'FaHippo', label: 'Hippo', component: FaHippo },
      { id: 'FaOtter', label: 'Otter', component: FaOtter },
      { id: 'FaFeatherAlt', label: 'Feather', component: FaFeatherAlt },
      { id: 'FaKiwiBird', label: 'Kiwi Bird', component: FaKiwiBird },
    ],
  },
  {
    label: 'People',
    icons: [
      { id: 'FaUser', label: 'User', component: FaUser },
      { id: 'FaUsers', label: 'Users', component: FaUsers },
      { id: 'FaUserFriends', label: 'User Friends', component: FaUserFriends },
      { id: 'FaChild', label: 'Child', component: FaChild },
      { id: 'FaBaby', label: 'Baby', component: FaBaby },
      { id: 'FaUserTie', label: 'User Tie', component: FaUserTie },
      { id: 'FaUserGraduate', label: 'Graduate', component: FaUserGraduate },
    ],
  },
  {
    label: 'Tools',
    icons: [
      { id: 'FaWrench', label: 'Wrench', component: FaWrench },
      { id: 'FaHammer', label: 'Hammer', component: FaHammer },
      { id: 'FaCog', label: 'Gear', component: FaCog },
      { id: 'FaScrewdriver', label: 'Screwdriver', component: FaScrewdriver },
      { id: 'FaClipboard', label: 'Clipboard', component: FaClipboard },
      { id: 'FaRulerCombined', label: 'Ruler', component: FaRulerCombined },
      { id: 'FaIndustry', label: 'Industry', component: FaIndustry },
      { id: 'FaHardHat', label: 'Hard Hat', component: FaHardHat },
      { id: 'FaFlask', label: 'Flask', component: FaFlask },
    ],
  },
];

export const ICON_REGISTRY: Record<string, IconType> = Object.fromEntries(
  ICON_GROUPS.flatMap((g) => g.icons.map((i) => [i.id, i.component])),
);

export const ICON_LABEL_MAP: Record<string, string> = Object.fromEntries(
  ICON_GROUPS.flatMap((g) => g.icons.map((i) => [i.id, i.label])),
);

export function isIconId(value: string): boolean {
  return value in ICON_REGISTRY;
}
